#!/bin/sh

# mkdevicemap - make a device.map for GRUB, find GRUB menus

INSTALL="$1"

# Create a device.map file
rm -f ${INSTALL}/boot/grub/device.map
mkdir -p ${INSTALL}/boot/grub
${INSTALL}/sbin/grub --batch --no-floppy \
        --device-map=${INSTALL}/boot/grub/device.map &>/dev/null <<EOF
quit
EOF

# Report device.map contents
cat ${INSTALL}/boot/grub/device.map

for p in /boot/grub/menu.lst /grub/menu.lst /boot/grub/grub.cfg /grub/grub.cfg; do
    # Search all partitions for /boot/grub/menu.lst
    ${INSTALL}/sbin/grub --batch --no-floppy \
            --device-map=${INSTALL}/boot/grub/device.map \
            2>/dev/null <<EOT | grep '(h' | sed "s|(|+++ ${p} (|"
find ${p}
quit
EOT
done
