#!/bin/bash

# Build a self-contained pacman package, containing the necessary support
# libraries, as a replacement for the no longer provided 'pacman.static'.

allin=pacman-allin.tar.gz

echo ""
read -p  "Have you checked that mirrorlist is up to date? [y/N]: " ans
if [ -z "$( echo ${ans} | grep '^ *[yY]' )" ]; then exit 0; fi

pacmanx=$( which pacman )
basepath=opt/larch
libpath=$basepath/lib
rm -rf ${basepath%%/*}
mkdir -p $libpath

mkdir $basepath/data
cp mirrorlist $basepath/data

for lib in $( ldd $pacmanx | grep "=> /" | \
        sed -r "s|.*=> ([^ ]*).*|\1|" ); do
    cp $lib $libpath
done

cp $pacmanx $libpath
cp /lib/libnss_files.so.2 $libpath
cp /lib/ld-linux*.so.2 $libpath/loader

mkdir $basepath/run
cp $( which repo-add ) $basepath/run
cp pacman.sh $basepath/run/pacman
chmod 755 $basepath/run/pacman

tar -czf $allin ${basepath%%/*}

rm -rf ${basepath%%/*}

echo "$allin should now be ready"
