#!/bin/sh

APP="$( basename $0 )"
# Get path to this script
FULLPATH="$( readlink -f $0 )"
SCRIPTDIR="$( dirname ${FULLPATH} )"

cd ${SCRIPTDIR}/../modules

# I've put this in to make the packaging easier, but it
# might be better to byte compile.
export PYTHONDONTWRITEBYTECODE=x

if [ ${UID} -eq 0 ]; then
    cmd=""
elif $( which gksu &>/dev/null ); then
    cmd="gksu "
elif $( which gksu &>/dev/null ); then
    cmd="kdesu "
else
    echo "larch must be run with root privileges." 1>&2
    echo "  Try installing gksu or kdesu." 1>&2
    echo "  You could also try 'su -c ./larch' in a terminal." 1>&2
    exit 1
fi

${cmd} python larch.py &>/dev/null &
