#!/bin/sh

APP="$( basename $0 )"
# Get path to this script
FULLPATH="$( readlink -f $0 )"
SCRIPTDIR="$( dirname ${FULLPATH} )"

cd ${SCRIPTDIR}/../modules

# I've put this in to make the packaging easier, but it
# might be better to byte compile.
export PYTHONDONTWRITEBYTECODE=x

if [ ${UID} -eq 0 ]; then
    exec python larch.py "$@"
else
    if [ "$1" != "-c" ] && [ "$1" != "-f" ]; then
        if $( which gksu &>/dev/null ); then
            exec gksu -- python larch.py "$@"
        elif $( which kdesu &>/dev/null ); then
            exec kdesu -- python larch.py "$@"
        fi
    else
        echo "larch must be run with root privileges." 1>&2
        echo "You could try 'su -c \"./larch <options>\"'" 1>&2
        echo " ... but double-quotes in the command must be escaped."  1>&2
        exit 1
    fi
fi

echo "larch must be run with root privileges." 1>&2
echo "  Try installing gksu or kdesu." 1>&2
echo "  You could also try 'su -c ./larch' in a terminal." 1>&2
exit 1
