#!/bin/bash

# usb2bootiso

# This generates a boot iso for a larch USB-stick. This can be used to
# allow the USB-stick to be used on computers which can't boot from USB.

#===================================================================
# 2009.08.24

# UNDER CONSTRUCTION


APP="$( basename $0 )"
FULLPATH="$( readlink -f $0 )"
SCRIPTDIR="$( dirname ${FULLPATH} )"

mkiso ()
{
    mkisofs -r -l $1 \
        -no-emul-boot -boot-load-size 4 -boot-info-table \
        -input-charset=UTF-8 \
        -publisher "designed by gradgrind, licence: GPL" \
        -A "larch-7" \
        -o "bootcd.iso" "${CDDATA}"

    if [ $? -eq 0 ]; then
        echo "// Your ISO has been created as $( pwd )/bootcd.iso"
    else
        echo "ERROR: iso build failed" 1>&2
        return 1
    fi
}


CDDATA=$( pwd )/bootcd
rm -rf ${CDDATA}

# Find USB-stick



# Determine whether isolinux or grub
if [ -d ${MP}/syslinux ]; then
    mkdir -p ${CDDATA}/isolinux

    cp -r ${MP}/syslinux/* ${CDDATA}/isolinux &>/dev/null

    if ! cp ${MP}/usr/lib/syslinux/isolinux.bin ${CDDATA}/isolinux; then
        echo "Couldn't find isolinux.bin, is 'syslinux' installed?"
        exit 1
    fi

    mkiso "-b isolinux/isolinux.bin -c isolinux/isolinux.boot"

elif [ -d ${MP}/syslinux ]; then



else
    echo "ERROR: doesn't look like a bootable larch partition"
fi
