#!/bin/sh

# 0killr   - recursive killing of child processes

apath="$( readlink -f $0 )"
adir="$( dirname ${apath} )"
ppp="$( pgrep -P $1 )"
echo "killing $1">>/tmp/killed
kill -9 $1
for pid in ${ppp}; do
    "${adir}/0killr" ${pid}
done
