#!/bin/sh

# fdisk-l

# Get the general disk info returned by 'fdisk -l' applied to device $1
#
LANG=C fdisk -l $1

#*******************************************************
#  -> something like:
#
#   Disk /dev/sdb: 64.9 GB, 64901611520 bytes
#   255 heads, 63 sectors/track, 7890 cylinders
#   Units = cylinders of 16065 * 512 = 8225280 bytes
#   Disk identifier: 0x000480d2
#
#      Device Boot      Start         End      Blocks   Id  System
#   /dev/sdb1               1          20      160618+  83  Linux
#   /dev/sdb2              21          56      289170    f  W95 Ext'd (LBA)
#   /dev/sdb5              21          56      289138+  83  Linux
#
#*******************************************************
