#!/bin/sh

# get-devices

# For each device return a line with ':'-separated device, size, device type

for dev in $( cat /proc/partitions | grep "[sh]d[a-z]$" | sed "s|.* ||" ); do
    op=$( LANG=C parted /dev/$dev print | grep -m2 "" )
    m=$( echo $op | sed "s|.*Model:\(.*\)Disk.*|\1|" )
    s=$( echo $op | sed "s|.*Disk.*:||" )
    echo /dev/$dev:$s:$m
done
