#!/bin/sh

# grubinstall

# Install grub to device $2
INSTALL="$1"

cat /proc/mounts | grep ${INSTALL} | sed "s|[^ ]*${INSTALL}/*|/|" | \
    sed "s|//|/|" >${INSTALL}/etc/mtab
chroot ${INSTALL} /sbin/grub-install --no-floppy $2
ret=$?
: >${INSTALL}/etc/mtab
exit ${ret}
