#!/bin/sh

# newpart

# Create a new partition on the given device (argument $1)
# $2 - start position (cylinders)
# $3 - end position (cylinders)
# $4 - fstype (ext2/linux-swap/... absent for extended partition)
# $5 - primary/logical/extended
parted -s $1 unit cyl mkpart $5 $4 $2 $3
