#!/bin/sh

# part-format

# Format a partition (argument $1), file-system type $2, options $3

# For fs=ext3 and fs=ext4
fmtext ()
{
    mkfs.${fs} $1

    if [ "$1" != "/" ]; then
        tune2fs -m 1 $1
    fi

    if [ ${fs} = "ext3" ]; then
        journal_data="ordered"
    else
        journal_data=""
    fi
    diri="yes"
    opts="$2"

    while [ -n "${opts}" ]; do
        o=${opts:0:1}
        opts=${opts:1}
        case ${o} in
            I ) # no directory indexing
                diri="" ;;
            W ) journal_data="writeback" ;;
            O ) journal_data="ordered" ;;
            * ) echo "Unknown ${fs} option: ${o}"
                return 1 ;;
        esac
    done

    if [ -n "${diri}" ] && ! tune2fs -O dir_index $1; then
        echo "Directory indexing failed"
        return 1
    fi
    if [ -n "${journal_data}" ] && ! tune2fs -o journal_data_${journal_data} $1; then
        echo "Setting journal_data_${journal_data} failed"
        return 1
    fi
    return 0
}

p=$1
f=$2
o=$3
case ${f} in
    ext4 ) fs="ext4" ; fmtext ${p} ${o} ;;
    ext3 ) fs="ext3" ; fmtext ${p} ${o} ;;
    reiserfs ) mkreiserfs -q ${p} ;;
    ext2 ) mke2fs ${p} ;;
    jfs ) mkfs.jfs -q ${p} ;;
    xfs ) mkfs.xfs -f ${p} ;;
    * ) echo -n "Bad arguments: ${p} ${f} ${o}"
        false ;;
esac
