#!/bin/sh

# part-format

# Format a partition (argument $1), file-system type $2
p=$1
f=$2

case ${f} in
    ext4 ) mkfs.ext4 ${p} ;;
    ext3 ) mkfsext3 ${p} ;;
    reiserfs ) mkreiserfs -q ${p} ;;
    ext2 ) mke2fs ${p} ;;
    jfs ) mkfs.jfs -q ${p} ;;
    xfs ) mkfs.xfs -f ${p} ;;
    * ) echo -n "Bad arguments: ${p} ${f}"
        false ;;
esac
