#!/bin/sh

# part-tweak

# Tweak a partition (argument $1), ... ???
# TODO!!!

# For fs=ext3 and fs=ext4
fmtext ()
{
    if [ "$1" != "/" ]; then
        tune2fs -m 1 $1
    fi

    if [ ${fs} = "ext3" ]; then
        journal_data="ordered"
    else
        journal_data=""
    fi
    diri="yes"
    opts="$2"

    while [ -n "${opts}" ]; do
        o=${opts:0:1}
        opts=${opts:1}
        case ${o} in
            I ) # no directory indexing
                diri="" ;;
            W ) journal_data="writeback" ;;
            O ) journal_data="ordered" ;;
            * ) echo "Unknown ${fs} option: ${o}"
                return 1 ;;
        esac
    done

    if [ -n "${diri}" ] && ! tune2fs -O dir_index $1; then
        echo "Directory indexing failed"
        return 1
    fi
    if [ -n "${journal_data}" ] && ! tune2fs -o journal_data_${journal_data} $1; then
        echo "Setting journal_data_${journal_data} failed"
        return 1
    fi
    return 0
}

