#!/bin/sh

# xkmap-set - run this during X start to set the keyboard selected by xkmap
#             for the current user

if echo "$1" | grep ':' &>/dev/null; then
    layout="${1%:*}"
    variant="${1#*:}"
    if [ "${variant}" != "-" ]; then
        varg="-variant ${variant}"
    else
        varg=""
    fi
    setxkbmap -layout ${layout} ${varg}
fi
