#!/bin/bash
#
# larch-locales - Generate glibc locales to an overlay (a slightly tricky business)
#
#2009.08.21

# If there is a 'locales' file in the profile (which contains a list of the
# desired locales, like 'locale.gen') it will be used for the generation,
# being prefixed to a commented out version of the existing '/etc/locale.gen'.
# If there is no 'locales' file the existing '/etc/locale.gen' (in the
# system to be larchified!) will be used, which is empty by default.

# $1: path to system to be larchified ("" if running system)
# $2: path to profile directory
# $3: path to temporary overlay directory (where the overlay is being built)

INSTLDIR="$1"
PROFILEDIR="$2"
OVERLAYDIR="$3"

mkdir -p ${OVERLAYDIR}/etc
mkdir -p ${OVERLAYDIR}/usr/lib
echo
echo "********** Generating locales to an overlay **********"
echo
rm -f ${INSTLDIR}/etc/locale.gen_new
rm -Rf ${INSTLDIR}/usr/lib/locale.save
if [ -f ${PROFILEDIR}/locales ]; then
    echo "###+++ autogen"   >${INSTLDIR}/etc/locale.gen_new
    cat ${PROFILEDIR}/locales >>${INSTLDIR}/etc/locale.gen_new
    echo "###--- autogen" >>${INSTLDIR}/etc/locale.gen_new
    # Append the original file, with all lines commented out and lines
    # from '###+++' to '###---' deleted
    cat ${INSTLDIR}/etc/locale.gen | sed -e "/###+++/,/###---/ d" \
            -e "s|^\([^#].*\)|#\1|" >>${INSTLDIR}/etc/locale.gen_new

    mv -f ${INSTLDIR}/etc/locale.gen ${INSTLDIR}/etc/locale.gen_old
    mv -f ${INSTLDIR}/etc/locale.gen_new ${INSTLDIR}/etc/locale.gen
    cp ${INSTLDIR}/etc/locale.gen ${OVERLAYDIR}/etc
    cp -a ${INSTLDIR}/usr/lib/locale ${INSTLDIR}/usr/lib/locale.save
fi

if [ -n  "${INSTLDIR}" ]; then
    chroot ${INSTLDIR} /usr/sbin/locale-gen
else
    /usr/sbin/locale-gen
fi
cp -a ${INSTLDIR}/usr/lib/locale ${OVERLAYDIR}/usr/lib
# /usr/lib/locale will be excluded from system.sqf

# Restore old locale files
if [ -f ${INSTLDIR}/etc/locale.gen_old ]; then
    mv -f ${INSTLDIR}/etc/locale.gen_old ${INSTLDIR}/etc/locale.gen
    rm -Rf ${INSTLDIR}/usr/lib/locale
    mv ${INSTLDIR}/usr/lib/locale.save ${INSTLDIR}/usr/lib/locale
fi

