#!/bin/bash
#
# larch-initcpio - Generate initcpio (using chroot if necessary)
#
#2009.08.08


# $1: path to system to be larchified ("" if running system)
# $2: path to profile directory
# $3: path to temporary overlay directory (where the overlay is being built)
# $4: unioning file system type, '_aufs' or '_unionfs'

INSTLDIR="$1"
PROFILEDIR="$2"
OVERLAYDIR="$3"
UFS="$4"

# Fix up larch mkinitcpio.conf for unionfs/aufs
mcf0=${INSTLDIR}/etc/mkinitcpio.conf.larch0
if [ -f ${PROFILE}/mkinitcpio.conf ]; then
    mcf0=${PROFILE}/mkinitcpio.conf
fi
sed "s|___aufs___|${UFS}|g" <${mcf0} >${INSTLDIR}/etc/mkinitcpio.conf.larch

presets=( $( cd ${INSTLDIR}/etc/mkinitcpio.d ; echo kernel26*.preset ) )
if [ ${#presets[@]} -ne 1 ]; then
    echo "Error: Couldn't find usable /etc/mkinitcpio.d/kernel26*.preset"
    return 1
fi
# Save original preset file (unless a '*.larchsave' is already present)
pfile=( $( ls ${INSTLDIR}/etc/mkinitcpio.d/*.larchsave 2>/dev/null ) )
if [ ${#pfile[@]} -ne 1 ]; then
    mkdir -p ${OVERLAYDIR}/etc/mkinitcpio.d
    cp ${INSTLDIR}/etc/mkinitcpio.d/${presets} ${OVERLAYDIR}/etc/mkinitcpio.d/${presets}.larchsave
fi

# Adjust larch.preset file for custom kernels
sed "s|___|${presets%.preset}|" <${INSTLDIR}/etc/mkinitcpio.d/larch.preset0 >${INSTLDIR}/etc/mkinitcpio.d/larch.preset

# Replace 'normal' preset in overlay
cp ${INSTLDIR}/etc/mkinitcpio.d/larch.preset ${OVERLAYDIR}/etc/mkinitcpio.d/${presets}

# Generate initramfs
if [ -n  "${INSTLDIR}" ]; then
    chroot ${INSTLDIR} /sbin/mkinitcpio -p larch
else
    /sbin/mkinitcpio -p larch
fi

